version: '3'

networks:
  net1:
    name: net1
    driver: bridge

services:

  load_balancer:
    build: ./Load-balancer
    container_name: load_balancer
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - net1

  dummy:
    build: ./server
    image: fastapi-server
    entrypoint: ["sleep", "infinity"]
    networks:
      - net1
    deploy:
      replicas: 0
